FROM node:20.12.0-alpine3.19

# Set the working directory to the client app
WORKDIR /usr/src/app

# Copy the package files specific to the client app
COPY ./package.json ./package-lock.json ./tsconfig.json ./

# Install the dependencies for the client app
RUN npm install

# Copy the rest of the client app files
COPY ./ .

# Build the client app
RUN npm run build

# Start the client app
CMD ["npm", "run", "start"]
